### ISSUE TITLE
make_dict自造词选字问题

### ISSUE THREAD

**Issue by ZeroLaboratory** [X1aomu/rime-uggx#1]
pinyin_simp 拼音反查可以数字选词，但是make_dict自造词选字的时候就不行了，数字直接进入输入框，不知道还有没有的救😄️

**Comment by X1aomu** [comment]
感谢反馈，已找到原因，目前使用「X」作为造词缀与默认的「upppercase」识别器冲突，目前找到的解决方式有两种：

1. 不使用大写字母做为前缀，转而使用其他符号
2. 不使用预置的「upppercase」识别器，副作用是输入大写字母会直接上屏，这样必须切换到英文模式才可以输入像「Rime」这样的以大写开头的英文单词

关于这两种方案的选择，你有什么建议吗？

第二种方式我已经将修改提交到一个新的分支 https://github.com/X1aomu/rime-uggx/commit/8dcd3a3d666041287ad76711155531d048a38fe8 ，可以试用一下😄️ @ZeroLaboratory

**Comment by X1aomu** [comment]
感谢反馈，已找到原因，目前使用「X」作为反查前缀与默认的「upppercase」识别器冲突，目前找到的解决方式有两种：

1. 不使用大写字母做为前缀，转而使用其他符号
2. 不使用预置的「upppercase」识别器，副作用是输入大写字母会直接上屏，这样必须切换到英文模式才可以输入像「Rime」这样的以大写开头的英文单词

关于这两种方案的选择，你有什么建议吗？

**Comment by ZeroLaboratory** [comment]
Nice😄️，感谢作者回复，

1. 受作者启发，还有一种解决方案如下:
    make_dcit 与 uppercase pattern 无法区分，可删除uppercase pattern 中的 “ ‘” 字符
2. 建议:取消顶字上屏与自动清空。
    原因:会对import_preset中的email pattern 产生影响：
    例如: uggxhodv...blabla@gmail.com类似的邮箱只能切换到英文模式才可以输入。 

 修改如下：
`speller:
    delimiter: " '"
    # max_code_length: 4  # 设置最大码长 开启此选项可以实现顶字上屏
    auto_select: false  # 是否自动上屏
    # auto_clear: max_length  # 输入全码长无候选时自动清空
    ......
  recognizer:
    import_preset: default
    patterns:
      uppercase: "[A-Z][-_+.0-9A-Za-z]*$"
      punct: '^/([0-9]|10|[A-Za-z]+)$'  # / 开头识别为符号。
    # make_dict: "^[a-z]+'.+$"  # 含 "'" 时启用手动造词
    make_dict: "X[a-z']*$"  # 含 "'" 时启用手动造词
    pinyin_simp: "`[a-z']*$"  # 反查引導鍵 以 ` 开头
`
github不怎么会用😭️，不会做diff，作者将就着看吧😄️

**Comment by X1aomu** [comment]
> make_dcit 与 uppercase pattern 无法区分，可删除uppercase pattern 中的 “ ‘” 字符

这个方法不错。

> 建议:取消顶字上屏与自动清空

`uggx` 方案如果取消顶字上屏的话将会变得非常难用，每敲完四个编码就要按一下空格才能上屏，我个人在输入邮箱时也习惯切英文。另外 `uggx` 主要是为快速输入单字使用的，对喜欢快速打单字和固定单字位置的人群比较讨喜。

这个仓库中还有 `uggx_fluency` 方案，默认使用连打和自造词，就像在 `uggx` 方案中按下了「X」一样，但是连打体验要更好。这个用法相对日常些，`email` 、 `uppercaes` 、 `url` 这些预置识别器也都可以正常起作用。

其实我现在大部分时间都在使用 `uggx_fluency` 方案，就是仓库页面还没做介绍😂️

所以，我打算对 `uggx` 方案取消预置的识别器（uppercase、email 和 url 这几个），单独补充一个改进的 uppercase 识别器，因为在顶字上屏的情况下 email 和 url 几乎没有用武之地了。

**Comment by X1aomu** [comment]
> 建议:取消顶字上屏与自动清空。
> 原因:会对import_preset中的email pattern 产生影响：
> 例如: uggxhodv...blabla@gmail.com类似的邮箱只能切换到英文模式才可以输入。

补充：对于你说的这个情况，除了不使用 email 识别器之外，还有一个折衷方案。

那就是将，`auto_clear: max_length` 这一行注释掉，这样输入四码后如果无候选将允许继续输入，而如果输入四码后有候选存在，继续键入其他字母将会顶字上屏。

+ 如输入「nrzya」，因为「你好」是「nrzy」的第一候选，所以结果为「你好」被上屏，「a」留在输入区。
+ 如输入「ugge@a.com」，因为「ugge」没有匹配的候选，所以整个「ugge@a.com」都将留在输入区，
